### ISSUE TITLE
AzCopy Sync does not upload changed file to blob storage

### ISSUE THREAD

**Issue by mazong1123** [Azure/azure-storage-azcopy#165]
### Which version of the AzCopy was used? 
AzCopy 10.0.5-Preview

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Server 2016

### What command did you run?
cmd /c C:\azcopy_windows_amd64_10.0.5\azcopy.exe sync e:\test https://{storageaccount}.blob.core.windows.net/testblobs/test --recursive=true --force=true 

### What problem was encountered?
The file change cannot be synced to the blob storage.

### How can we reproduce the problem in the simplest way?
- Create a file testsync.txt in e:\test. Put the content `123` into it.
- Run the command.
- Update the file testsync.txt, change the content to `123abc`.
- Run the command.

#### Expected
The contents of testsync.txt in testblobs blob storage is `123abc`

#### Actual
The contents of testsync.txt in testblobs blob storage is `123`

### Have you found a mitigation/solution?
No.

**Comment by zezha-msft** [comment]
Hi @mazong1123, thanks for reaching out!

I've logged this issue for further investigation.

**Comment by mazong1123** [comment]
@zezha-msft Thanks. This issue seems impacts the major scenario that is the **update** function is generally broken. Please let me know if I can help in anyway as `AzCopy Sync` looks promising for our scenario.

**Comment by mazong1123** [comment]
Bump. Any update for this bug? Failed to sync the change of a file is kind of a major issue of AzCopy Sync. Or this cannot be reproduced from your side? I'm evaluating AzCopy as our major sync tool but this is blocking me to propose it. I'm willing to work closely with you guys to address this issue. Thanks :)

**Comment by mazong1123** [comment]
Hi, I tried the new 1.0.0.6-preview release, the bug still persists. Is there any timeline for fixing this bug? Just want to know whether it can catch up our timeline. Thanks.

**Comment by zezha-msft** [comment]
Hi @mazong1123, sorry I haven't merged in the fix yet. It will go out with the next release, which should be this or next Friday. Is this ok for your timeline?

**Comment by mazong1123** [comment]
Hi @zezha-msft , seems the issue still exist in 1.0.0.7-preview. Just want to confirm whether the fix was included in the 1.0.0.7 release. Thanks!

**Comment by zezha-msft** [comment]
Hi @mazong1123, sorry for the delay. I had to rewrite some part of the code. The fix will be out with 10.0.8.

**Comment by mazong1123** [comment]
@zezha-msft Thank you!

**Comment by Kapanther** [comment]
@zezha-msft and @mazong1123 Am I write in assuming that if destination has a later DATE MODIFIED then the source the file it will not overwrite?

**Comment by zezha-msft** [comment]
Hi @Kapanther, yes! If the file at the destination has a later last modified time, then we wouldn't perform the transfer. Did you encounter this bug too?

**Comment by Kapanther** [comment]
@zezha-msft yes i did. Thought i was doing something stupid again.  V10.0.7.

**Comment by zezha-msft** [comment]
No worries @Kapanther, these sync bugs are all fixed and will go out with 10.0.8.

**Comment by Kapanther** [comment]
@zezha-msft cant wait to test that release.. eta like less than a week?

Might be able to finally get rid of this crappy powershell syncing script of mine

**Comment by zezha-msft** [comment]
Hi @mazong1123 sorry for the inconvenience, and I really appreciate your patience!

I've rewritten the sync command and released it in 10.0.8. This issue should be fixed. Please let us know if you still encounter any problem.

Here is a [wiki](https://github.com/Azure/azure-storage-azcopy/wiki/Sync-command-guide) explaining how the new sync command works. Please feel free to reach out if you have any question or concern.

**Comment by mazong1123** [comment]
@zezha-msft Thank you! I verified the bug has been fixed.

**Comment by talhajilal** [comment]
Hi,  I am still facing same issue for this  "azcopy sync" command.

azcopy version 10.4.3


Issue : I create a text file "test_abc.txt" content "Changelog 1" 

Command "azcopy sync "source_dir" "dest_url" --recursive=true   --delete-destination=true     --put-md5

test_abc.txt uploaded. 

After some time, I change "test_abc.txt" content and re-run the same azcopy sync command, new content of the file not uploaded or updated at destination ( Blob) storage. 


Any tip what I am doing wrong ? 

Thanks,

**Comment by talhajilal** [comment]
> @zezha-msft Thank you! I verified the bug has been fixed.

Not fixed, Please check my post I am using 10.4.3
