### ISSUE TITLE
azcopy.exe : panic: runtime error: invalid memory address or nil pointer dereference when copying disks across regions

### ISSUE THREAD

**Issue by amelhilu** [Azure/azure-storage-azcopy#2404]
##### Note: The version is visible when running AzCopy without any argument
Tested using Azcopy Version 10.21.0 & 10.15.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Tested using Windows and Cloud Shell
"azure-cli": "2.53.0",
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
`
.\azcopy.exe copy $sourceSASURI $targetSASURI --blob-type PageBlob
`
 
### What problem was encountered?
Operation failed with the following Error:
.\azcopy.exe : panic: runtime error: invalid memory address or nil pointer dereference
At line:1 char:1
+ .\azcopy.exe copy $sourceSASURI $targetSASURI --blob-type PageBlob
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (panic: runtime ...ter dereference:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x2b2620]
goroutine 1 [running]:
net/url.(*URL).String(0x0)
	C:/hostedtoolcache/windows/go/1.19.12/x64/src/net/url/url.go:807 +0x40
github.com/Azure/azure-storage-azcopy/v10/cmd.copyHandlerUtil.ConstructCommandStringFromArgs({})
	D:/a/1/s/cmd/copyUtil.go:111 +0x407
github.com/Azure/azure-storage-azcopy/v10/cmd.init.2.func2(0xc000319680?, {0xc000363100?, 0x2?, 0x4?})
	D:/a/1/s/cmd/copy.go:1937 +0x1d6
github.com/spf13/cobra.(*Command).execute(0xc000319680, {0xc0003630c0, 0x4, 0x4})
	C:/Users/VssAdministrator/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x1580340)
	C:/Users/VssAdministrator/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	C:/Users/VssAdministrator/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/Azure/azure-storage-azcopy/v10/cmd.Execute({0xc0000ea900?, 0xc00006c110?}, {0xc0000ea940?, 0xd3935d?}, 0x74?, {0x4b348e4a, 0x4e38, 0xb342, {0x55, 0xc0, ...}})
	D:/a/1/s/cmd/root.go:189 +0x106
main.main()
	D:/a/1/s/main.go:84 +0x4ea

### How can we reproduce the problem in the simplest way?
Issue is reproducible on different subscriptions and different disks following the sample script attached. 
### Have you found a mitigation/solution?
We moved the disks to different region using Azure Storage explorer which seems to work with no issues. 

[azcopy_issue.txt](https://github.com/Azure/azure-storage-azcopy/files/12843498/azcopy_issue.txt)

**Comment by gapra-msft** [comment]
The panic should be resolved by the above PR and will be release as part of our next release, which should allow you to see the url that is causing an error parsing

**Comment by gapra-msft** [comment]
Closing this for now as this will be resolved as part of our next release.

**Comment by bfox-sugarshot** [comment]
This is still an issue in 10.23.0. I'm using SAS for both source and destination.

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104c6f3a0]

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/v10/cmd.(*blobTraverser).Traverse(0x140001a2230, 0x0?, 0x0?, {0x1057e1ae0, 0x0, 0x0})
	github.com/Azure/azure-storage-azcopy/v10/cmd/zc_traverser_blob.go:231 +0x570
github.com/Azure/azure-storage-azcopy/v10/cmd.(*CopyEnumerator).enumerate(0x14000337f40)
	github.com/Azure/azure-storage-azcopy/v10/cmd/zc_enumerator.go:766 +0x48
github.com/Azure/azure-storage-azcopy/v10/cmd.(*CookedCopyCmdArgs).processCopyJobPartOrders(0x14000418d80)
	github.com/Azure/azure-storage-azcopy/v10/cmd/copy.go:1610 +0xb5c
github.com/Azure/azure-storage-azcopy/v10/cmd.(*CookedCopyCmdArgs).process(0x140001da990?)
	github.com/Azure/azure-storage-azcopy/v10/cmd/copy.go:1262 +0x74
github.com/Azure/azure-storage-azcopy/v10/cmd.init.2.func2(0x14000423b80?, {0x140004ea0e0?, 0x2?, 0x104c856f6?})
	github.com/Azure/azure-storage-azcopy/v10/cmd/copy.go:2014 +0x1b0
github.com/spf13/cobra.(*Command).execute(0x14000423b80, {0x140004ea0a0, 0x2, 0x2})
	github.com/spf13/cobra@v1.4.0/command.go:860 +0x550
github.com/spf13/cobra.(*Command).ExecuteC(0x10574be80)
	github.com/spf13/cobra@v1.4.0/command.go:974 +0x318
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.4.0/command.go:902
github.com/Azure/azure-storage-azcopy/v10/cmd.Execute({0x140000dd4e0?, 0x10573a290?}, {0x140000dd560?, 0x104ccd51c?}, 0x74?, {0xd7bc6443, 0x83f4, 0xf447, {0x78, 0x5d, ...}})
	github.com/Azure/azure-storage-azcopy/v10/cmd/root.go:220 +0x104
main.main()
	github.com/Azure/azure-storage-azcopy/v10/main.go:84 +0x3a4`

**Comment by gapra-msft** [comment]
@bfox-sugarshot from the stack trace this looks unrelated to the original issue. Please open a new issue with more details so we can investigate further.

**Comment by bfox-sugarshot** [comment]
@gapra-msft https://github.com/Azure/azure-storage-azcopy/issues/2606

Thank you
