### ISSUE TITLE
azcopy.exe v10.27.0 memory usage

### ISSUE THREAD

**Issue by ep-ss-2021** [Azure/azure-storage-azcopy#2855]
Hi,

It was noticed that 10.27.0 azcopy.exe version forces 16GB RAM Windows Azure VirtualScale Set instances (AzureDevOps agents) to show "Free memory is lower than 5%" pipeline warning after ~1h of execution during long Azure storage account cross containers copying operation.
It happens from Thursday 31-Oct-2024. Previous 10.26.0 version works fine.
The following agent log fragment of last in in-memory record was shown for one of the pipeline failures:
"/golang.org/toolchain@v0.0.1-go1.23.1.windows-amd64/src/runtime/proc.go: 424, time.go: 285, asm_amd64.s:1700"
As the version had 'Golang 1.22.5 -> 1.23.1' dependency update, not sure if it can be related.

Thanks

**Comment by gapra-msft** [comment]
Hi @ep-ss-2021 Does your workload consist of a large directory structure/many directories?

**Comment by gapra-msft** [comment]
No, that's not necessary. 

The only AzCopy feature that I can think of that increased memory requirements is [this](https://github.com/Azure/azure-storage-azcopy/pull/2828). 

We now cache folder names to reduce redundant calls to create directories. 

Does the warning result in the job entirely failing? Would you be able to share how much memory AzCopy v10.26 used vs v10.27?

**Comment by ep-ss-2021** [comment]
Hi Gauri,

Yes, the agents entirely fail after ~1-1.5h with 'out of memory' or 'stack overflow error' plus 'We stopped hearing from agent XXXX. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error.' AzureDevOps pipeline level error messages on the step where we used azcopy.
The agent has Standard D4ds_v5 Azure SKU (16 GB of RAM), the usage is checked in task manager after several minutes of azcopy process start:
1.  **v10.26 case:**
       1.1)  after 2 mins the agent has 20% of RAM used, the process consumes 50-90% CPU + 0.9Gb RAM.
       1.2)  after 5 mins the agent has 20% of RAM used, the process consumes 50-90% CPU + 0.9Gb RAM.
2.  **v10.27 case:**
       2.1) after 2 mins the agent has 40% of RAM used, the process consumes 80-90% CPU + 4Gb RAM.
       2.2) after 5min the agent has 90% of RAM used, the process consumes 80-90% CPU + 9Gb RAM.

Thanks,
Sergey

**Comment by gapra-msft** [comment]
@ep-ss-2021 Could you please share logs for the v10.26 and v10.27 runs? That might help expediate investigation here. You can email them to azcopydev AT microsoft.com

**Comment by gapra-msft** [comment]
Hi @ep-ss-2021 We just released a patch which should resolve the issue. Please upgrade to 10.27.1

**Comment by ep-ss-2021** [comment]
Hi Colleagues,
Still the same error with 10.27.1. I'll try to raise a standard MS request and mention you, so MS can take the logs from exact agent instances.
Thanks,
Sergey.

**Comment by sarbiaAtAdobe** [comment]
Hi there, I've been impacted by OOMs with both 10.27.0 and 10.27.1 when copying from a storage container with millions of blobs, and I'm using a Linux VM with 128GB of RAM allocated. No issues with smaller storage containers, but in this case RAM availability was quickly nosediving resulting in consistently repeatable OOMs. 10.26.0 worked always fine in this regard and I have now downgraded to that release to complete the cross-blob-storage copy I had to perform.

**Comment by ep-ss-2021** [comment]
Hi Gauri,
   I've just created MS ticket, so hope the corresponding team finds you internally, so we can have a session tomorrow if you are free.
Thanks,
Sergey

**Comment by sarbiaAtAdobe** [comment]
For the record, I could complete my azcopy copy using 10.26.0 (and, as a side note, it would be nice if it were easier to locate older binaries). So definitely not an issue with what I was attempting to copy, but rather with the software I was using to attempt my copy.

**Comment by keikohashizume** [comment]
We have faced the same issue with both versions: 10.27.0 and 10.27.1
It is the same scenarion where we copying hundreds of thousand of files.
@sarbiaAtAdobe did you get it to work with 10.27.1?

**Comment by sarbiaAtAdobe** [comment]
Thanks @keikohashizume, as per my previous messages "I've been impacted by OOMs with both 10.27.0 and 10.27.1" and "I could complete my azcopy copy using 10.26.0". Unfortunately, this issue we're commenting on has been closed, unsure if there's an open one for MSFT to address this. What I can say is that with a blob count in the hundreds of thousands, I could complete copies even with 10.27.0 (but I'm using a 128GB RAM VM). But when we get to tens of millions, even 128GBs are not enough. It's clearly a memory leak.
I'm sticking to 10.26 for the foreseeable future, it would be good to find an open issue to track in order to see when this will actually be resolved.

**Comment by ep-ss-2021** [comment]
Hi Colleagues,
Let me share some updates: I've raised an official ticket with Microsoft and addressed this (logs, trace). So that's under investigation. I've also highlighted for the MS team colleagues that probably that issue should be reopened here.

**Comment by gidiLuke** [comment]
Thanks @ep-ss-2021 
Looking forward to hearing an update once you got a reply.

**Comment by ep-ss-2021** [comment]
Hi @gapra-msft , @seanmcc-msft , Could you reopen that issue as assume it's not resolved yet based on the MS ticket?

**Comment by echee-insitro** [comment]
We confirmed that a 30M object, 1.5TB server-to-server copy of s3-->blobstore has a reproducible memory leak (fails on both 32 GB & 128 GB clients).  Client machines become unresponsive due to OOM.  

The same dataset successfully copies when replacing azcopy binary with version 10.25.1 (running on the 128 GB client, system RAM maxes at 3GB).

**Comment by vibhansa-msft** [comment]
In 10.28.0 we are downgrading to 10.22.7 as the Go library itself has an issue with respect to high memory usage.
