### ISSUE TITLE
I am trying to resume a broken job on AzCopy v10

### ISSUE THREAD

**Issue by yallos** [Azure/azure-storage-azcopy#319]
### What command did you run? .\azcopy jobs resume 1a890bcc-5a40-f548-50cd-ad53f7a467c9 ?xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
.\azcopy jobs resume <jobid> --sourcesastokenhere --destinationsastokenhere  ***But Im copying from my local PC to Azure Storage Account so i only have destination token***

### What problem was encountered?
this command requires jobId to be passed as argument
'ss' is not recognized as an internal or external command,
operable program or batch file.
'srt' is not recognized as an internal or external command,
operable program or batch file.
'sp' is not recognized as an internal or external command,
operable program or batch file.
'se' is not recognized as an internal or external command,
operable program or batch file.
'st' is not recognized as an internal or external command,
operable program or batch file.
'spr' is not recognized as an internal or external command,
operable program or batch file.
'sig' is not recognized as an internal or external command,
operable program or batch file.
![image](https://user-images.githubusercontent.com/49304408/55615256-74e26280-577e-11e9-82b3-e6670b3a5f89.png)

### How can we reproduce the problem in the simplest way?
Initiate a Copy from C: drive of PC to Azure storage account and try to resume the Job using Job ID afterwards.

### Have you found a mitigation/solution?
No. Not yet

**Comment by seguler** [comment]
Your SAS token needs to be put in quotes. The $ signs in the token breaks your command (escapes out of the command)

**Comment by yallos** [comment]
Thanks for the Assistance @seguler 
I may have found the fix!!!!

Document is misguiding and it took me a while to figure it out 
https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#view-and-resume-jobs

The Document didn't specify the commands correctly or even show an example
**Documentation says: .\azcopy jobs resume <jobid> --sourcesastokenhere --destinationsastokenhere**

Real Life: .\azcopy jobs resume "27ea1553-5357-144d-428e-XXXXXXXX" --source-sas "C:\Users\VIRUS\Documents\My Received Files" --destination-sas "?sv=2018-03-28&ss=XXXXXXXX=sco&XXXXXXXXXXXX&st=2019-04-05T17:48:07Z&spr=https&sig=FlO6PZNhJEqvWhzN47aaYBLvEkalxkUERPynbL3J0Oo%3D"

**Since i was transferring from my Local PC, the PC Path becomes the source token ID**

![image](https://user-images.githubusercontent.com/49304408/55648267-c10dc100-57d7-11e9-87b5-3a979c766d19.png)

I hope it helps somebody :) Its IT and these things happen sometimes. But we shouldn't assume that everybody can easily figure it out. Thanks a Billion

**Comment by zezha-msft** [comment]
Hi @yallos, you don't need a source-sas since the source is local.

**Comment by yallos** [comment]
> Hi @yallos, you don't need a source-sas since the source is local.

Thanks @zezha-msft already figured it out and resolved the issue.

**Comment by seguler** [comment]
Yes - I just realized the document is not clear enough. Will fix it.

**Comment by seguler** [comment]
Fixed

**Comment by yallos** [comment]
> Fixed

Thanks @seguler but i see the command is broken here in the documentation: 
![image](https://user-images.githubusercontent.com/49304408/55675192-b7a75600-58b6-11e9-8881-9e7085fd773c.png)

The working code should be: 
**.\azcopy jobs resume "<Job ID>" --source-sas "<Path of job Source>" --destination-sas "<SAS key of Storage Account>"**

Thanks!!!

**Comment by qudiransari** [comment]
The [document](https://docs.microsoft.com/bs-latn-ba/azure/storage/common/storage-use-azcopy-configure) is still not updated @JohnRusk . It shows as per below: 
azcopy jobs resume <job-id> --source-sas="<sas-token>"
azcopy jobs resume <job-id> --destination-sas="<sas-token>"

Where it should be
.\azcopy jobs resume "" --source-sas "Path of job Source" --destination-sas "SAS key of Storage Account"

**Comment by JohnRusk** [comment]
I'm puzzled by the corrected syntax that's proposed.  Can you explain why there there should be a _path_ in the source _SAS_?
