### ISSUE TITLE
Copy fails (CannotVerifyCopySource) when storage account firewall is enabled

### ISSUE THREAD

**Issue by nfriday** [Azure/azure-storage-azcopy#755]
Using azcopy 10.3.2 (Windows), with a storage account firewall enabled on the source and destination, copy (or sync) between file shares fails with CannotVerifyCopySource.

`azcopy copy https://nicktestsource.file.core.windows.net/source/test.txt?sv=2018-11-09&sig=<REDACTED>=2019-11-21T10%3A07%3A46Z&se=2020-11-21T10%3A07%3A46Z&srt=sco&ss=f&sp=racupwdl https://nicktestdest.file.core.windows.net/dest/test.txt?sv=2018-11-09&sig=<REDACTED>&st=2019-11-21T10%3A01%3A58Z&se=2020-11-21T10%3A01%3A58Z&srt=sco&ss=f&sp=racupwdl`

Copy fails with:
```
INFO: Authentication failed, it is either not correct, or expired, or does not have the correct permission -> github.com/Azure/azure-storage-file-go/azfile.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.6.0/azfile/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=CannotVerifyCopySource) =====
Description=This request is not authorized to perform this operation.
RequestId:b50a48eb-701a-0026-2f53-a0d39d000000
Time:2019-11-21T10:07:49.6641367Z, Details: 
   Code: CannotVerifyCopySource
   PUT https://nicktestdest.file.core.windows.net/dest/test.txt?comp=range&se=2020-11-21t10%3A07%3A46z&sig=-REDACTED-&sp=racupwdl&srt=sco&ss=f&st=2019-11-21t10%3A07%3A46z&sv=2018-11-09&timeout=901
   Content-Length: [0]
   User-Agent: [AzCopy/10.3.2 Azure-Storage/0.6.0 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [3f5dbe62-5b0a-4528-6a02-3b891c5f387b]
   X-Ms-Copy-Source: [https://nicktestsource.file.core.windows.net/source/test.txt?se=2020-11-21t10%3A07%3A46z&sig=-REDACTED-&sp=racupwdl&srt=sco&ss=f&st=2019-11-21t10%3A07%3A46z&sv=2018-11-09]
   X-Ms-Range: [bytes=0-4]
   X-Ms-Source-Range: [bytes=0-4]
   X-Ms-Version: [2019-02-02]
   X-Ms-Write: [update]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: [248]
   Content-Type: [application/xml]
   Date: [Thu, 21 Nov 2019 10:07:48 GMT]
   Server: [Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [3f5dbe62-5b0a-4528-6a02-3b891c5f387b]
   X-Ms-Error-Code: [CannotVerifyCopySource]
   X-Ms-Request-Id: [b50a48eb-701a-0026-2f53-a0d39d000000]
   X-Ms-Version: [2019-02-02]
```

Problem can be replicated by attempting a copy between shares on different storage accounts which both have a storage account firewall configured.

Disabling the storage account firewall on both the source and destination works.

**Comment by adreed-msft** [comment]
Hi there! Because we make use of the Put*FromURL APIs available in Azure storage, the destination should be capable of reaching the source storage account.

Please ensure this is possible, and try again.

**Comment by nfriday** [comment]
The source and destination are both Azure files shares.

It is not possible (as far as I know) to configure the source storage account's firewall to allow access to the destination's storage account.

Am I therefore correct to understand that what I am trying to do is impossible?

![image](https://user-images.githubusercontent.com/49071468/69330367-b3178e00-0c4a-11ea-99b5-e3062238dbdf.png)

**Comment by JohnRusk** [comment]
It's only impossible in the short term.  A change is currently rolling out to the Azure Files service. Once that change is rolled out, it should work like this:

1. The machine where AzCopy is running needs to be able to access the source account. (Naturally).
2. The machine running AzCopy needs to be able to access the destination account (Naturally).
3. As long as the above conditions are met, then the account to account copy will work (with no other firewall config). Effectively it will use the IP address of the AzCopy client machine to authorize the source to destination traffic.  I.e. it will magically and securely work, without you needing to tell one storage account about the other.

I don't know exactly when this change will finish rolling out.  If you have a particularly urgent need, please email me and I'll make some inquiries for you.  My email address is in my profile page.

cc @adreed-msft This config change is good news, and will resolve the issue you mentioned above with no effort from users.

**Comment by JohnRusk** [comment]
The config change is not yet available. I'm investigating other workarounds.  Please reply here if you need details.

**Comment by nfriday** [comment]
Hi John, I'm interested in any workarounds you might find!

**Comment by JohnRusk** [comment]
I'm making some enquiries to find a workaround using AzCopy v10, if possible.   In the meantime, you could consider temporarily using the older version (AzCopy version 8.1).  It has totally different command line syntax, and its Account to Account copy operations are not as quick and convenient as V10s because it uses older Storage APIs.  But, conveniently in this case, the older APIs are not affected by this issue.  So I'm told they should work right now in the above-mentioned Storage Firewall configuration.

By default, V8 asks the Storage Service to copy asynchronously from the source to destination.  There's no SLA for how long the copy can take.  IIRC, it can take up to a week (but is typically much less. Details of the Async copy are documented on the Azcopy v8 documentation page). Or, if you use the /sync option, it downloads the files to the machine running AzCopy and streams them immediately back up to the destination.  (If using /sync, it’s probably best to run AzCopy on a medium-sized cloud VM, rather than on-premise, to avoid any potential bandwidth restrictions of your on-prem network link).


Note that V8 is effectively a totally different product from v10, with a different command line syntax.

**Comment by JohnRusk** [comment]
Update: there isn't any short-term workaround in V10.  I'm re-opening this issue, to remind us to post an update here when the Service-side issue is resolved. When that is resolved, v10 will work and we can close this issue.

**Comment by amarnathkarthik** [comment]
@JohnRusk is there a workaround available to copy the data between storage accounts?

**Comment by JohnRusk** [comment]
Server-side resolution should be enabled in most (if not all) places by now.  But, if you also have Private Link, then there is still an issue. See https://github.com/Azure/azure-storage-azcopy/issues/1003

**Comment by aplex** [comment]
@JohnRusk , can AzCopy V8 work when there is a firewall and a private link, or it has the same problems as AzCopy V10?

**Comment by JohnRusk** [comment]
I believe issue #1003 applies to AzCopy v8 too, since it uses one of the affected APIs, but I have not tested.  If you have followup questions, please ask them on that issues thread. Thanks.

**Comment by bruceharrison1984** [comment]
I'm having this same issue, but within some C# code. Both storage accounts are part of the same Vnet. One is a normal storage account, the other is a DataLake. Executing the copy always returns a "404 - CannotVerifyCopySource". Opening both firewalls doesn't correct the issue either.

**Comment by zffocussss** [comment]
azcopy version 10.3.4 can work ,while the new version v10.8.0 can not work @JohnRusk

**Comment by zffocussss** [comment]
it is strange linux v10.8.0 can work as well.but it failed some hours ago.what happened?

**Comment by JohnRusk** [comment]
@zffocussss please log a new issue for your recent failure.

**Comment by bahadir-be** [comment]
I have a similar issue.

**Comment by zezha-msft** [comment]
Should be fixed by now: https://azure.microsoft.com/en-us/updates/copy-blob-support-over-private-endpoints/

**Comment by slee-fdx** [comment]
Still experiencing this issue when trying to transfer from blob container to blob container in two separate private endpoints. 

Using a computer that can access both the source and destination (e.g. I can use `azcopy list ...` to both containers), I fail when trying to copy from source to destination with an authorization failure. Appears to still be an issue with the destination storage account sending the PUT request?

**Comment by akuma8** [comment]
I just experienced this issue with the Java SDK in a Spring Boot app, my goal is just to copy blob in the same container

**Comment by nestorochoa** [comment]
Same situation with the nodejs library, Im trying to copy a file from a storage blob that is with a private endpoint to a public one
`const SASURL = await sourceBlob.generateSasUrl({
        permissions: BlobSASPermissions.parse('racwd'),
        expiresOn,
      });
      const response = await destinationBlob.beginCopyFromURL(SASURL);`
And I just get the same error "CannotVerifyCopySource", I followed the steps mentioned earlier and read the documentation from Microsoft that says that this is possible, but still have the same issues.
There is some workaround to this?

**Comment by asmaier** [comment]
Why is this ticket closed? This issue and #1673 are not fixed.

**Comment by qfChenMSFT** [comment]
works when both storage in the same region but have problem when copy cross region

**Comment by sanmai-NL** [comment]
@JohnRusk Can you reopen this issue please?

**Comment by JohnRusk** [comment]
@sanmai-NL I moved to a different team a few years ago.  @adreed-msft, can you take a look at the comments above and reply here please?

**Comment by andrew-allen-work** [comment]
This is outstandingly poor IMHO ... copy from a to b in the cloud should be as simple as an old dos style copy folder a to folder b ... 
Private link endpoints have given no end of issues not a well thought out design more of an after thought bolt on... 
I've spent a few weeks getting all our on prem and azure firewalls opened up to allow a copy from one SA to another cloud side and this still seems to be an issue getting on for 3 YEARS after it was first reported. ... #PoorCustomerService

**Comment by tompaana** [comment]
I think this issue should be reopened. I don't want to create yet another duplicate issue as this and #1673 already exist. I have created a "project" that can be quickly deployed to Azure to reproduce this problem: https://github.com/tompaana/blob-copy-test

**Comment by siminsavani-msft** [comment]
Hi all! This issue is not something AzCopy can fix or handle. The destination cannot read the source in this scenario. The best solution is to whitelist IPs as mentioned in this thread. Please view this documentation for additional information: https://github.com/Azure/azure-storage-azcopy/wiki/Troubleshooting---FAQ#firewallprivate-endpoint-issues

**Comment by balintbako** [comment]
We see the same issue in private networking setup (no public IP's to white-list). AzCopy fails with 403 where the VM, sitting in a VNET, can access both storage accounts.

**Comment by mnit016** [comment]
I faced this issue 403 when work in private cloud, but the weird thing is some storages work, some not

I have 3 storages and try to use azcopy sync the File between 2 storages.
Storage A: Standard_LRS Central 
Storage B: Standard_GRS East2US
Storage C: Premium_LRS East2US
**They're same network configuration at all**
- azcopy B -> A - success
- azcopy B -> C - failed
- azcopy A -> C - failed

**Comment by sakthivs1** [comment]
> I faced this issue 403 when work in private cloud, but the weird thing is some storages work, some not
> 
> I have 3 storages and try to use azcopy sync the File between 2 storages. Storage A: Standard_LRS Central Storage B: Standard_GRS East2US Storage C: Premium_LRS East2US **They're same network configuration at all**
> 
> * azcopy B -> A - success
> * azcopy B -> C - failed
> * azcopy A -> C - failed

@mnit016 Whether A and B accounts firewall is not enabled and Firewall is enabled in account C. Could you please confirm?

**Comment by S0meth1ng85** [comment]
> Still experiencing this issue when trying to transfer from blob container to blob container in two separate private endpoints.
> 
> Using a computer that can access both the source and destination (e.g. I can use `azcopy list ...` to both containers), I fail when trying to copy from source to destination with an authorization failure. Appears to still be an issue with the destination storage account sending the PUT request?

Hi. Did you find a resolution for this?
In my case azcopy copy works as expected from SA A to SA B. But if I am trying to restore files in opposite direction I receive this PUT error. 
Both accounts have Private endpoints for blob configured. Private dns zone created and linked to both subnets. Subents are in different VNets with VNET peering and traffic enabled in both directions. No NSG assigned to the subnets.
`2024/02/29 08:47:59 ==> REQUEST/RESPONSE (Try=1/38.008222ms, OpTime=50.727271ms) -- RESPONSE STATUS CODE ERROR
   PUT 
   <URL>
   Accept: application/xml
   Content-Length: 0
   User-Agent: AzCopy/10.21.0 azsdk-go-azblob/v1.1.0 (go1.19.12; linux)
   X-Ms-Client-Request-Id: 1b72a72b-1c9f-4a44-65fd-b1f59be57412
   x-ms-blob-condition-appendpos:
   x-ms-copy-source:
   x-ms-source-range:
   x-ms-version:
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: 251
   Content-Type: application/xml
   Date: Thu, 29 Feb 2024 08:47:58 GMT
   Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
   X-Ms-Client-Request-Id: 1b72a72b-1c9f-4a44-65fd-b1f59be57412
   X-Ms-Error-Code: CannotVerifyCopySource
   X-Ms-Request-Id: 7a63831a-301e-00a0-55eb-6ac321000000
   X-Ms-Version: 2020-10-02
Response Details: ﻿<?xml version="1.0" encoding="utf-8"?> <Error><Code>CannotVerifyCopySource</Code><Message>Could not verify the copy source within the specified time. </Message>`

**Comment by jugganutz** [comment]
I've been fighting similar things.

**My environment:**
_Hub-Spoke network design_

- Transit VNET/Hub was created with Azure VWAN with Secure-Hub
- VNET1/Subnet1(Dedicated Private Endpoint subnet) (Spoke1) Production
- VNET2/Subnet1(Dedicated Private Endpoint subnet) (Spoke2) Dev
- VNET3/Subnet1 (VM running in dedicated subnet) (Spoke3) Utility 
- Private DNS zone for "privatelink.blob.core.windows.net" is linked to hub spokes that run custom DNS services. 
- SecuredHub/Azure Firewall has been configured to utilize DNS services in hub spoke. 
- VNET1/VNET2/VNET3 all have DNS configured to use Azure SecuredHub. 

**What I am trying to solve:** 
I need to copy some data from Storage Account 1 in Production to Storage Account 2 in Dev. Both storage accounts have private endpoint in VNET1 and VNET2 as described above. They all use the same Private DNS zone that is utilized by the whole environment for DNS resolution to private endpoint connections. I am trying to utilize a hardened VM in VNET3 to act as a proxy to run a scheduled task to copy files between production and dev. 

**Issues I have run into.**
My utility VM that is running AZcopy has line of site access to both storage account 1 and 2 with private endpoints. I am able to manage the storage independently for both Storage account 1 and 2. The Azure firewall policies allow it etc. 
As this thread has shown. I am getting the dreaded 403 on PUT. I have followed Microsoft documentation on my scenario. The documentation I have been using has been the following links, [We support it](https://azure.microsoft.com/en-us/updates/copy-blob-support-over-private-endpoints/), [Constraints](https://learn.microsoft.com/en-us/azure/storage/common/storage-private-endpoints#storage-access-constraints-for-clients-in-vnets-with-private-endpoints), [Client's vnet has private links configured.](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/copy-blobs-between-storage-accounts-network-restriction#scenario-2-the-clients-vnet-has-private-links-configured-and-it-uses-a-private-endpoint-to-access-storage-accounts)

None of those links/documentation directly worked, and I found them pretty poorly diagramed or very small-scale lab like designed. 

**My workaround that seems to work**

- Added Private Link connection to Storage Account 2. The private link should be in the production Spoke1/VNET1/Subnet1 where the production storage has a private endpoint. 
- During the private endpoint creation for Storage Account 2. Do not add DNS for this connection. Note, by doing this, Azure will remove the original DNS record for the original private endpoint connection. You will have to go to the DNS zone for privatelink.blob.core.windows.net and re-add the DNS record manually for Storage Account 2 (dev IP's name etc) to keep the dev applications that consume Storage Account 2 working. As Azure Firewall is blocking Dev from Production network wise. 
- On the Utility VM, create a hostfile entry for dev.privatelink.blob.core.windows.net that points to the new private endpoint IP that resides in Spoke1/VNET1/Subnet1

Once the Utility VM running AZcopy in Spoke3/Vnet3/subnet1 is accessing storage for both storage accounts in Spoke1/Vnet1/subnet1 it works flawlessly.

**Comment by DenisBalan** [comment]
Still this thing happens, and no logs in firewall from dest storage account

simply failing with CannotVerifyCopySource
