### ISSUE TITLE
Azure Storage Explorer : 403 This request is not authorized to perform this operation using this permission. whith 1.11 version

### ISSUE THREAD

**Issue by ghost** [Azure/azure-storage-azcopy#790]
### Which version of the AzCopy was used? 
Azure Storage Explorer 1.11
AzCopy 10.3.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10 1909

### What command did you run?
Job-Command copy C:\Users\xxxxxxx\Downloads\S3100-9.11.3.0-Config.pdf https://xxxxxxxxxxxx.blob.core.windows.net/ingestiondata/S3100-9.11.3.0-Config.pdf?se=2020-01-11t11%3A53%3A09z&si=ingestionsasforazcopy201912061529080283&sig=-REDACTED-&sr=c&sv=2015-04-05 --output-type=json --overwrite=prompt --cancel-from-stdin --follow-symlinks --recursive --from-to=LocalBlob --blob-type=BlockBlob --put-md5 

Launched by Azure Storage Explorer

### What problem was encountered?
When I upload a file using a SAS key generated from O365 importation page with Azure Storage Explorer 1.11, I encounter this error : 
 403 This request is not authorized to perform this operation using this permission.
If I use the same SAS key in Azure Storage Explorer 1.9, it's okay.

### Have you found a mitigation/solution?
Using The 1.9 version.

AzCopy log file : 
2019/12/12 11:58:28 AzcopyVersion  10.3.2
2019/12/12 11:58:28 OS-Environment  windows
2019/12/12 11:58:28 OS-Architecture  amd64
2019/12/12 11:58:28 Log times are in UTC. Local time is 12 Dec 2019 12:58:28
2019/12/12 11:58:28 Job-Command copy C:\Users\xxxxxx\Downloads\S3100-9.11.3.0-Config.pdf https://xxxxxxx.blob.core.windows.net/ingestiondata/S3100-9.11.3.0-Config.pdf?se=2020-01-11t11%3A53%3A09z&si=ingestionsasforazcopy201912061529080283&sig=-REDACTED-&sr=c&sv=2015-04-05 --output-type=json --overwrite=prompt --cancel-from-stdin --follow-symlinks --recursive --from-to=LocalBlob --blob-type=BlockBlob --put-md5 
2019/12/12 11:58:28 Number of CPUs: 4
2019/12/12 11:58:28 Max file buffer RAM 2.000 GB
2019/12/12 11:58:28 Max concurrent network operations: 32 (Based on number of CPUs. Set AZCOPY_CONCURRENCY_VALUE environment variable to override)
2019/12/12 11:58:28 Check CPU usage when dynamically tuning concurrency: true (Based on hard-coded default. Set AZCOPY_TUNE_TO_CPU environment variable to true or false override)
2019/12/12 11:58:28 Max concurrent transfer initiation routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_FILES environment variable to override)
2019/12/12 11:58:28 Max open files when downloading: 2147483311 (auto-computed)
2019/12/12 11:58:28 JobID=18681fc3-509b-a040-59ff-04875c176011, credential type: Anonymous
2019/12/12 11:58:28 PERF: primary performance constraint is Unknown. States: R:  0, D:  0, W:  0, F:  0, B:  0, E:  0, T:  0, GRs:  0
2019/12/12 11:58:28 scheduling JobID=18681fc3-509b-a040-59ff-04875c176011, Part#=0, Transfer#=0, priority=0
2019/12/12 11:58:28 INFO: [P#0-T#0] has worker 6 which is processing TRANSFER
2019/12/12 11:58:28 INFO: [P#0-T#0] Starting transfer: Source "%5C%5C?\\C:\\Users\\xxxxx\\Downloads\\S3100-9.11.3.0-Config.pdf" Destination "https://xxxxxxxx.blob.core.windows.net/ingestiondata/S3100-9.11.3.0-Config.pdf?se=2020-01-11t11%3A53%3A09z&si=ingestionsasforazcopy201912061529080283&sig=-REDACTED-&sr=c&sv=2015-04-05". Specified chunk size 8388608
2019/12/12 11:58:28 ==> REQUEST/RESPONSE (Try=1/15.9593ms, OpTime=98.7374ms) -- RESPONSE STATUS CODE ERROR
   HEAD https://xxxxxxxxx.blob.core.windows.net/ingestiondata/S3100-9.11.3.0-Config.pdf?se=2020-01-11t11%3A53%3A09z&si=ingestionsasforazcopy201912061529080283&sig=-REDACTED-&sr=c&sv=2015-04-05&timeout=901
   User-Agent: [AzCopy/10.3.2 Azure-Storage/0.7 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [86bf19be-d76b-4df2-5ba0-17200bbb32af]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation using this permission.
   Date: [Thu, 12 Dec 2019 11:58:28 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   Vary: [Origin]
   X-Ms-Error-Code: [AuthorizationPermissionMismatch]
   X-Ms-Request-Id: [7ee9bdf0-201e-003c-6ae3-b0b91b000000]
   X-Ms-Version: [2018-03-28]
Response Details: 

2019/12/12 11:58:28 ERR: [P#0-T#0] UPLOADFAILED: %5C%5C?\C:\Users\xxxxxxx\Downloads\S3100-9.11.3.0-Config.pdf : 000 : Could not check file existence. -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthorizationPermissionMismatch) =====
Description=403 This request is not authorized to perform this operation using this permission., Details: (none)
   HEAD https://xxxxxxxx.blob.core.windows.net/ingestiondata/S3100-9.11.3.0-Config.pdf?se=2020-01-11t11%3A53%3A09z&si=ingestionsasforazcopy201912061529080283&sig=-REDACTED-&sr=c&sv=2015-04-05&timeout=901
   User-Agent: [AzCopy/10.3.2 Azure-Storage/0.7 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [86bf19be-d76b-4df2-5ba0-17200bbb32af]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation using this permission.
   Date: [Thu, 12 Dec 2019 11:58:28 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   Vary: [Origin]
   X-Ms-Error-Code: [AuthorizationPermissionMismatch]
   X-Ms-Request-Id: [7ee9bdf0-201e-003c-6ae3-b0b91b000000]
   X-Ms-Version: [2018-03-28]

**Comment by JohnRusk** [comment]
To narrow down the cause, can you tell us please, when you used Storage Explorer 1.9, did you have AzCopy enabled or disabled?  (In that version, I believe it only used AzCopy if you enabled the AzCopy integration).

**Comment by EricF2** [comment]
Hello,
I used the 1.9 in july and august. I tried it few days because the 1.11 showed an error during upload.
I doesn't activate AzCopy in the 1.9, I use the default parameters.

**Comment by JohnRusk** [comment]
@adreed-msft any chance you can reproduce this?

**Comment by EricF2** [comment]
All my transfers are concerned by this error in the 1.11.

**Comment by adreed-msft** [comment]
This is an error to check the file existence when the Overwrite setting is false or prompt.

It looks like your SAS token uses a signed identifier pattern-- My guess is, judging from a prior user's issue in a similar scenario, that your SAS token is Write-only. To fix this, overwrite should be true, and you should disable destination length checking. (--overwrite=true --check-length=false)

**Comment by adreed-msft** [comment]
Please tell me if this helps your scenario @EricF2

**Comment by duttong13** [comment]
@adreed-msft We have also noticed this issue with Azure Storage explorer 1.12 where write and list permissions for a SAS token are not enough to upload a file to blob.

Can you let me know if this is planned to be resolved in an upcoming release of storage explorer?

**Comment by datsabk** [comment]
This issue is noticed in my case when the blob name is different from the file name that is being uploaded - Using Java SDK for Blob storage.

**Comment by JohnRusk** [comment]
@datsabk if your issue relates to the Java SDK, I suggest you search for the right place to log it. (This isn't that place ;-)  This is only for AzCopy v10)

**Comment by duttong13** [comment]
@JohnRusk @adreed-msft This issue is still occuring even in v.1.13 where it was noted that https://github.com/microsoft/AzureStorageExplorer/issues/2336 had been resolved and a prompt was created. Can you investigate this further please.

**Comment by JohnRusk** [comment]
@dttong13 In the current version of AzCopy, the solution is as per this comment above: https://github.com/Azure/azure-storage-azcopy/issues/790#issuecomment-569799061 

Unfortunately, in Storage Explorer, I can't see any setting turn off the length check.

In the next version of AzCopy, it will automatically handle the situation, without the need to change the length check setting.

**Comment by duttong13** [comment]
@JohnRusk Thanks for getting back so quickly. 

Is there any update on when storage explorer will be able to leverage the next version of AzCopy? What would the version number be, so I can keep an eye out for it?

Current workaround for others: Use Storage Explorer v1.9

**Comment by JohnRusk** [comment]
The AzCopy version number that you want will probably 10.5.  (Although we might sneak it out in 10.4.something. If you subscribe to updates to the AzCopy releases pages, you'll be notified when all releases ship, and can check the release notes that are published there).  

Sometime after that, Storage Explorer will release a version that includes the AzCopy update.

**Comment by duttong13** [comment]
@JohnRusk Do you have an estimated ETA for such a release? This is just so we can keep our customers informed on when they can expect to update their storage explorer to v1.14 i imagine?

**Comment by JohnRusk** [comment]
No, I don't sorry. We don't generally publish ETAs on the AzCopy team.  IIRC the Storage Explorer team also generally don't publish ETAs.

**Comment by duttong13** [comment]
This issue is now resolved in release v1.14. Please feel free to close this issue record

**Comment by TheAnahaym** [comment]
Hi duttong13
I've installed version 1.14 and still have this issue.

```
   Dst: https://link
2020/06/27 14:32:52 JobID=ID, Part#=0, TransfersDone=1 of 2
2020/06/27 14:32:52 ==> REQUEST/RESPONSE (Try=1/37.0021ms, OpTime=185.6622ms) -- RESPONSE STATUS CODE ERROR
   HEAD https://link
   User-Agent: [Microsoft Azure Storage Explorer, 1.14.0, win32,  AzCopy/10.4.2 Azure-Storage/0.7 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [ID]
   X-Ms-Version: [2019-02-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation using this permission.
   Date: [Sat, 27 Jun 2020 14:32:52 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   Vary: [Origin]
   X-Ms-Client-Request-Id: [ID]
   X-Ms-Error-Code: [AuthorizationPermissionMismatch]
   X-Ms-Request-Id: [ID]
   X-Ms-Version: [2019-02-02]
Response Details: 

2020/06/27 14:32:52 ERR: [P#0-T#0] UPLOADFAILED: some.pst : 000 : Could not check destination file existence. -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthorizationPermissionMismatch) =====
Description=403 This request is not authorized to perform this operation using this permission., Details: (none)
   HEAD https://link
   User-Agent: [Microsoft Azure Storage Explorer, 1.14.0, win32,  AzCopy/10.4.2 Azure-Storage/0.7 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [ID]
   X-Ms-Version: [2019-02-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation using this permission.
   Date: [Sat, 27 Jun 2020 14:32:52 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   Vary: [Origin]
   X-Ms-Client-Request-Id: [ID]
   X-Ms-Error-Code: [AuthorizationPermissionMismatch]
   X-Ms-Request-Id: [36d5b801-601e-002f-188f-4c2e6d000000]
   X-Ms-Version: [2019-02-02]

```

**Comment by Triamus** [comment]
I had a similar issue but it went away with 1.14 (before I was on 1.9).

**Comment by TheAnahaym** [comment]
Hi Triamus,
I've installed v1.14 on several servers and workstations: it doesn't work anywhere. I will install v1.14 on a server where it has never been installed

**Comment by Triamus** [comment]
@TheAnahaym however my issue was that connecting to blob via sas token in azure storage explorer gui didn't work and now it does.

**Comment by don4of4** [comment]
This is also happening in the 1.14.2 version of Azure storage explorer (AzCopy 10.5).

**Comment by smohr003** [comment]
Getting similar errors in Explorer 1.14.2. Unable to retrieve child resources.

```
Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:35d64ee9-b01e-0060-2d7f-6aecc1000000\nTime:2020-08-04T16:51:45.0261360Z</Message></Error>
```
i think there is problem with API endpoints. I am receiving the same error when try to programatically access the blob as well. The weird thing is that I can access everything with an older version of Storage Explorer, 1.12.0

**Comment by don4of4** [comment]
This issue may be caused by not having “Storage Blob Delegator.”

**Comment by lakal-malimage** [comment]
Check Storage account firewall .  Temporarily disable it and try .

**Comment by gpacetti** [comment]
Add the "Storage Blob Data Contributor" role if you want to write it.  https://azure.microsoft.com/it-it/blog/azure-storage-support-for-azure-ad-based-access-control-now-generally-available/

**Comment by adreed-msft** [comment]
Closing due to longevity. If the issue is still present and still requires support, feel free to re-open.
