### ISSUE TITLE
Overwrite set to ifSourceNewer not working for File Shares

### ISSUE THREAD

**Issue by Timothyoverton** [Azure/azure-storage-azcopy#910]
### Which version of the AzCopy was used? 
azcopy version 10.3.4

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10

### What command did you run?
.\azcopy.exe copy "https://tim.file.core.windows.net/[SAS]" "https://timdestination.file.core.windows.net/[SAS]" --recursive --overwrite=ifSourceNewer

### What problem was encountered?
I'm copying several word documents from one Azure file share to another file share. Editing word documents on the source file share and running the statement above does not copy over the edited files. If I change the name of the document then it does copy it over. If I add a new document, then it does copy over as well. The modified date isn't being respected.

### How can we reproduce the problem in the simplest way?
Edit the source of a  file, which updates the modified date. File does not copy over.

### Have you found a mitigation/solution?
None. Haven't tested if its working for blobs.

**Comment by JohnRusk** [comment]
Hi Tim.  Just to help us narrow down what might be happening here, could you try a test where there's more time between when you edit the file and when you run AzCopy. E.g. 24 hours or so.  Just to rule in or out any role that small time differences may play.

**Comment by Timothyoverton** [comment]
Hi John, yes I did try that today, I thought timezone differences might be at play as well, the example above was from yesterday and when I started today, I reran the script, 20 hours later, the modified file still did not copy over.

**Comment by Timothyoverton** [comment]
The other thing I've tried, is modifying the file in different way, I've uploaded a modified file through the Az Portal, overwriting the source file. And I've modified the file by mapping a drive to the share and modifying the file from the share directly, both methods of modification don't result in a file being copied over. The modified date in the Az Portal does update though, doing the mod either way, for the source file when viewing it in the Az Portal.

**Comment by JohnRusk** [comment]
Is "azcopy sync" an option for you? In some cases, e.g. high file count, it's better to use copy with the IfSourceNewer flag.  But if sync suited you, it could be an easy solution. (And if sync failed for you in the same way, that could be very informative.  I'm not sure what it would tell us, but definitely _something_)

**Comment by Timothyoverton** [comment]
Hi John, I was hoping to use _sync_ from the outset but unfortunately file share to file share isn't supported by _sync_

**Comment by JohnRusk** [comment]
File Share to File Share sync has been supported since version 10.3.0.  Do we still have documentation that says otherwise?

**Comment by Timothyoverton** [comment]
That's what I thought and had read, should this command work?
`.\azcopy.exe sync "https://tim.file.core.windows.net/[SAS]" "https://timdestination.file.core.windows.net/[SAS]" --recursive`

**Comment by JohnRusk** [comment]
Not as you've written it.  As you've written it, you're identifying _accounts_, not _shares_.

This would work
```
.\azcopy.exe sync "https://tim.file.core.windows.net/sourceshare[SAS]" "https://timdestination.file.core.windows.net/destshare[SAS]" --recursive
```

But, you you want to hit all shares in an account, IIRC that's not supported with Sync. I.e. this only works with copy (note the star).  IIRC We have a open feature request to make this work with Sync too.
```
.\azcopy.exe sync "https://tim.file.core.windows.net/*[SAS]" "https://timdestination.file.core.windows.net[SAS]" --recursive
```

**Comment by Timothyoverton** [comment]
Ok super, as you said, if I stipulate the share, then I can use sync and its successfully identifying and transferring only modified files. Great. 

I'd like to support the wildcard share option, I'd use that.

You still have an issue with ifSourceNewer but I can work with above, shall I close the ticket?

**Comment by JohnRusk** [comment]
Great to know that gives you a workable option.  Let's leave this issue open, to remind us to look into ifSourceNewer for file shares.

@zezha-msft Any thoughts on IfSourceNewer not working for Azure Files?

**Comment by oak13** [comment]
Hi,
I'm experiencing a similar issue; I'm using version 10.4.0 (2020/04/19) and trying to copy from Azure Files to Azure Blob storage (in different accounts) with azcopy copy with overwrite flag set to ifSourceNewer.

Despite changing a file in the source,  azcopy claims the “File already exists, so will be skipped”, and does not copy over.

**Comment by nakulkar-msft** [comment]
Fixed, #1091

**Comment by Timothyoverton** [comment]
Hi @nakulkar-msft - I'm running 10.6.0 - and I still can't get modified files to copy between storage account file shares using this command:
`azcopy.exe copy "https://tim.file.core.windows.net/abc?[SAS]" "https://timdestination.file.core.windows.net/abc?[SAS]" --overwrite=ifSourceNewer --recursive`

**Comment by Timothyoverton** [comment]
`azcopy sync` 
does copy work and copies over the modified files

**Comment by Timothyoverton** [comment]
Hi @nakulkar-msft - any update on the issue?

**Comment by zezha-msft** [comment]
@nakulkar-msft does this still repro?

**Comment by opeongo** [comment]
I am noticing that using `overwrite=ifSourceNewer` will still repeatedly copy the same unchanged files when copying from fileshare to local.  For example:
```
azcopy copy https://myaccount.file.core.windows.net/myshare/* c:/azure/myshare --preserve-last-modified-time --overwrite=ifSourceNewer --recursive
```

When I execute this command the first time all of the available files (10) are downloaded.
If I then execute the command a second time then the 5 largest files are downloaded again, and the 5 smallest files are skipped.
Repeatedly executing the command will always re-download the same 5 larger files.  The larger 5 files are still quite small ranging from 73Kb to 8Mb.

**Comment by gapra-msft** [comment]
Closing this issue as it looks like this is a duplicate of an issue that seems to have bene resolved already. Please feel free to reopen an issue in case you are still experiencing problems with ifSourceNewer for FileShares.
